### ISSUE TITLE
Wrong time format for launching

### ISSUE THREAD

**Issue by AndreaLibe** [c-hydro/fp-hyde#5]
https://github.com/c-hydro/fp-hyde/blob/7878d2ea8747df54b959639d0625744e55fa3c36/bin/downloader/gsmap/hyde_downloader_satellite_gsmap.py#L16

-time YYYYMMDDHHMM

**Comment by fabiodelogu** [comment]
I did not update the algorithm file because probably the correct grammar is:
-time "YYYY-MM-DD HH:MM" if users would like to use splitted date and time 
or
-time YYYYMMDDHHMM for merged date and time

Generally I think that the right use is:
-time "xyz"
I updated the example of command-line in the first part of the code.
